name: duolingo
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localization: any
  firebase_core: any
  firebase_database: ^10.2.3
  firebase_auth: ^4.4.2
  cloud_firestore: any
  cloud_functions: ^4.3.3
  email_validator:
  awesome_dialog: ^3.1.0
  firebase_messaging: any
  cupertino_icons: any
  youtube_player_flutter: ^8.1.2
  just_audio: ^0.9.32
  audioplayers:
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/appBar/crown_stroke.png
  - assets/images/appBar/flag.png
  - assets/images/appBar/navbar_diamont.png
  - assets/images/appBar/navbar_fire.png

  #welcome
  - assets/images/logo-with-duo.png
  #social
  - assets/images/social/facebook.png
  - assets/images/social/google.png
  #home_screen
  - assets/images/home_screen/lesson_egg.png
  - assets/images/home_screen/lesson_airplane.png
  - assets/images/home_screen/store_item_8.png
  - assets/images/home_screen/lesson_hamburger.png
  - assets/images/home_screen/lesson_baby.png
  - assets/images/home_screen/lesson_dialog.png
  - assets/images/home_screen/lesson_divisor_castle.png
  #floating_action_button
  - assets/images/floating_action_button/tab_training_selected.png
  - assets/images/floating_action_button/tab_training.png
  #bottom_navigation_bar
  - assets/images/bottom_navigation_bar/tab_lessons_selected.png
  - assets/images/bottom_navigation_bar/tab_lessons.png
  - assets/images/bottom_navigation_bar/tab_profile_selected.png
  - assets/images/bottom_navigation_bar/tab_profile.png
  - assets/images/bottom_navigation_bar/tab_ranking_selected.png
  - assets/images/bottom_navigation_bar/tab_ranking.png
  - assets/images/bottom_navigation_bar/tab_store_selected.png
  - assets/images/bottom_navigation_bar/tab_store.png
  - assets/images/bottom_navigation_bar/tab_stories_selected.png
  - assets/images/bottom_navigation_bar/tab_stories.png
  - assets/images/CodeHub_Logo.png
  - assets/images/LOGO_MAIN.png
  - assets/images/Bunny_monitor_logo.gif
  - assets/images/Backend.gif
  - assets/images/Small_Logo.png
  - assets/images/Python.png
  - assets/images/C_sharp.png
  - assets/images/C+++.png
  - assets/images/Javascript.png
  - assets/images/Background.png
  - assets/images/ranks/a.png
  - assets/images/ranks/b.png
  - assets/images/ranks/d.png
  - assets/images/ranks/g.png
  - assets/images/ranks/i.png
  - assets/images/ranks/ir.png
  - assets/images/ranks/p.png
  - assets/images/ranks/r.png
  - assets/images/ranks/s.png
  - assets/images/white.png
  - assets/images/home.gif
  - assets/images/Trophy.gif
  - assets/images/lock.png
  - assets/images/mark.png
  - assets/images/Back_white.png
  - assets/Notification.mp3
  - assets/Correct_answer.mp3
  - assets/Wrong_answer.mp3
  #exams
  - assets/images/exams/igcse.png
  - assets/images/exams/ent.png
  #comps
  - assets/images/exams/comps/1.png
  - assets/images/exams/comps/2.png
  #numbers
  - assets/images/exams/topics/1.png
  - assets/images/exams/topics/2.png
  - assets/images/exams/topics/3.png
  - assets/images/exams/topics/4.png
  - assets/images/exams/topics/5.png
  - assets/images/exams/topics/6.png
  #may-31-june-1-hackathon
  - assets/images/kz/profile_kz.png
  - assets/images/kz/shit.png
  - assets/images/kz/book.png
  - assets/images/kz/FlagF.png
  - assets/images/kz/FlagS.png
  - assets/images/kz/profile_kzBez.png
  - assets/images/kz/shitBez.png
  - assets/images/kz/knigaBez.png
  - assets/images/kz/kozi.png
  - assets/images/kz/tarihnama.png
  - assets/images/kz/TN.png
  
  
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Futura
      fonts:
       - asset: fonts/ofont.ru_Futura Md.ttf
    - family: Bebas
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf
    - family: en
      fonts:
        - asset: fonts/feather_bold.ttf
    - family: Geo
      fonts:
        - asset: fonts/ofont.ru_Geologica.ttf
    - family: Kel_Regular
      fonts:
        - asset: fonts/Kelson_Sans_Regular.otf
    - family: kz
      fonts:
        - asset: fonts/Kelson_Sans_Bold.otf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
